export type AirportOption = {
  iata: string;
  name: string;
};

export const AIRPORT_OPTIONS: AirportOption[] = [
  { iata: "ATL", name: "Hartsfield-Jackson Atlanta" },
  { iata: "AUS", name: "Austin-Bergstrom" },
  { iata: "ANC", name: "Ted Stevens Anchorage" },
  { iata: "BOS", name: "Boston Logan" },
  { iata: "BWI", name: "Baltimore/Washington" },
  { iata: "CLT", name: "Charlotte Douglas" },
  { iata: "CVG", name: "Cincinnati/Northern Kentucky" },
  { iata: "DCA", name: "Ronald Reagan Washington National" },
  { iata: "DEN", name: "Denver" },
  { iata: "DFW", name: "Dallas/Fort Worth" },
  { iata: "DTW", name: "Detroit Metro" },
  { iata: "EWR", name: "Newark Liberty" },
  { iata: "FLL", name: "Fort Lauderdale" },
  { iata: "HNL", name: "Daniel K. Inouye Honolulu" },
  { iata: "IAD", name: "Washington Dulles" },
  { iata: "IAH", name: "George Bush Intercontinental" },
  { iata: "JFK", name: "John F. Kennedy" },
  { iata: "LAS", name: "Harry Reid Las Vegas" },
  { iata: "LAX", name: "Los Angeles" },
  { iata: "LGA", name: "LaGuardia" },
  { iata: "MCI", name: "Kansas City" },
  { iata: "MCO", name: "Orlando" },
  { iata: "MIA", name: "Miami" },
  { iata: "MSP", name: "Minneapolis-Saint Paul" },
  { iata: "MSY", name: "Louis Armstrong New Orleans" },
  { iata: "OAK", name: "Oakland" },
  { iata: "ORD", name: "Chicago O'Hare" },
  { iata: "PDX", name: "Portland" },
  { iata: "PHL", name: "Philadelphia" },
  { iata: "PHX", name: "Phoenix Sky Harbor" },
  { iata: "RDU", name: "Raleigh-Durham" },
  { iata: "SAN", name: "San Diego" },
  { iata: "SAT", name: "San Antonio" },
  { iata: "SEA", name: "Seattle-Tacoma" },
  { iata: "SFO", name: "San Francisco" },
  { iata: "SJC", name: "San Jose" },
  { iata: "SLC", name: "Salt Lake City" },
  { iata: "STL", name: "St. Louis Lambert" },
  { iata: "TPA", name: "Tampa" },
  { iata: "YUL", name: "Montreal Trudeau" },
  { iata: "YVR", name: "Vancouver" },
  { iata: "YYZ", name: "Toronto Pearson" },
  { iata: "AMS", name: "Amsterdam Schiphol" },
  { iata: "BCN", name: "Barcelona El Prat" },
  { iata: "CDG", name: "Paris Charles de Gaulle" },
  { iata: "DUB", name: "Dublin" },
  { iata: "FCO", name: "Rome Fiumicino" },
  { iata: "FRA", name: "Frankfurt" },
  { iata: "IST", name: "Istanbul" },
  { iata: "LGW", name: "London Gatwick" },
  { iata: "LHR", name: "London Heathrow" },
  { iata: "MAD", name: "Adolfo Suarez Madrid-Barajas" },
  { iata: "VIE", name: "Vienna" },
  { iata: "ZRH", name: "Zurich" },
  { iata: "AUH", name: "Abu Dhabi" },
  { iata: "CAI", name: "Cairo" },
  { iata: "CPT", name: "Cape Town" },
  { iata: "DEL", name: "Delhi" },
  { iata: "DOH", name: "Hamad" },
  { iata: "DXB", name: "Dubai" },
  { iata: "JNB", name: "O.R. Tambo" },
  { iata: "TLV", name: "Ben Gurion" },
  { iata: "AKL", name: "Auckland" },
  { iata: "BKK", name: "Suvarnabhumi" },
  { iata: "BOM", name: "Mumbai" },
  { iata: "CAN", name: "Guangzhou Baiyun" },
  { iata: "HKG", name: "Hong Kong" },
  { iata: "HND", name: "Tokyo Haneda" },
  { iata: "ICN", name: "Incheon" },
  { iata: "MEL", name: "Melbourne" },
  { iata: "NRT", name: "Tokyo Narita" },
  { iata: "PEK", name: "Beijing Capital" },
  { iata: "PVG", name: "Shanghai Pudong" },
  { iata: "SIN", name: "Singapore Changi" },
  { iata: "SYD", name: "Sydney" },
  { iata: "BOG", name: "El Dorado" },
  { iata: "GRU", name: "Sao Paulo Guarulhos" },
  { iata: "LIM", name: "Jorge Chavez" },
  { iata: "MEX", name: "Mexico City" },
  { iata: "SCL", name: "Santiago" },
];
